basePath: /
definitions:
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
  model.Machine:
    properties:
      age:
        type: string
      id:
        type: string
    required:
    - age
    - id
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for validation of machines-management
  title: machines-management-validator-backend
  version: "1.0"
paths:
  /api/machines/validate:
    post:
      consumes:
      - application/json
      description: validate list of machines and return only outlier machines
      parameters:
      - description: list of machines
        in: body
        name: input
        required: true
        schema:
          items:
            $ref: '#/definitions/model.Machine'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Machine'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Validate
      tags:
      - machines
swagger: "2.0"
